name: Python Unit Tests
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: python3 -m unittest discover
