name: Script Linter
on: [push]
jobs:
  Script-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: python3 -m unittest discover
